version: '3'

tasks:
  init:
    cmds:
      - wails init -n app -t svelte
      - (cd app; go mod edit -module app)
  doctor:
    cmds:
      - wails doctor
  run:
    dir: app
    cmds:
      - wails dev
  clean:
    cmds:
      - rm -rf app/
